<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/OnnxModelRuntime/OnnxModelRuntime.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../assets/mul_1.onnx" Link="mul_1.onnx" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
